spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: ElementService
        uri: lb://ElementService
        predicates:
        - Path=/element/**
      - id: RewardService
        uri: lb://RewardService
        predicates:
        - Path=/reward/**
      - id: SchoolService
        uri: lb://SchoolService
        predicates:
          - Path=/school/**
      - id: StudentService
        uri: lb://StudentService
        predicates:
          - Path=/student/**
      - id: TeacherService
        uri: lb://TeacherService
        predicates:
          - Path=/teacher/**
      - id: AvatarService
        uri: lb://AvatarService
        predicates:
          - Path=/avatar/**
      - id: UserService
        uri: lb://UserService
        predicates:
          - Path=/user/**
      - id: PurchaseService
        uri: lb://PurchaseService
        predicates:
          - Path=/order/**
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


