spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/michaelhenok/SA-Project
server.port: 8888



# https://github.com/michaelhenok/SA-Project
#C:\Users\alaza\Documents\config

