server:
  port: 7074

spring:
  application:
     name: AvatarService  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Avatar
  main:
    allow-bean-definition-overriding: true
